server:
  port: 9296
spring:
  application:
    name: CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fazal-haroon/microservices
          clone-on-start: true

#          Installing Zipkin via Docker -> docker run -d -p 9411:9411 openzipkin/zipkin

